# Generated by Django 5.1 on 2024-08-31 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_picture_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='Публичный'),
        ),
        migrations.AddField(
            model_name='picture',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='Публичное'),
        ),
    ]
